---
- name: 'Add mongodb repo 3.0 and up'
  yum_repository:
    name: "mongodb-org-{{ mongodb.mongodb_ver }}"
    description: "MongoDB Repository"
    baseurl: https://repo.mongodb.org/yum/{{ mongodb.os_family }}/{{ mongodb.os_ver }}/mongodb-org/{{ mongodb.mongodb_ver }}/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-{{ mongodb.mongodb_ver }}.asc
    file: mongodb-org-{{ mongodb.mongodb_ver }}
<<<<<<< HEAD
=======
  when: mongodb_ver|float() >= 3.0
>>>>>>> 546076c2d0f44d87f841ff8358b0655e8b06e9d1

- name: 'Install mongodb-org'
  package:
    name: mongodb-org
    state: latest
