---
env:
 RUNLEVEL: 1

mysql_pkgs:
  - libselinux-python
  - mariadb-server
  - MySQL-python

mysql_service: mysqld

mysql_conf_dir: "/etc/"

mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: foobar

mysql_db:
     - name: testdb
       replicate: yes

mysql_users:
     - name: testUser
       pass: test
       priv: "*.*:ALL"

mysql_sql_mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
