# Create temporary install folders
# this is required mostly when these
# scripts are mainly used to update
# Enterprise Gateway deployment
- name: create install dir
  file: path="{{ install_dir }}" state=directory

- name: create temporary install dir
  file: path="{{ install_temp_dir }}" state=directory

- name: download anaconda package
  get_url:
     url: "{{anaconda_download_url}}/{{ anaconda_install_file }}"
     dest: "{{ install_temp_dir }}/{{ anaconda_install_file }}"

- name: install anaconda package
  shell: "bash {{ install_temp_dir }}/{{ anaconda_install_file }} -b -p {{ install_dir }}/anaconda3"

# Environment setup.
- name: Add anaconda_env to startup
  template:
    src: anaconda-profile.sh.j2
    dest: /etc/profile.d/anaconda-profile.sh
    mode: 0644
