
- name: remove old java packages from OS
  shell:
     yum erase -y java-1.8.0-openjdk java-1.8.0-openjdk-headless

- name: set java distribution fact
  set_fact: java_install_file=jdk-{{ common.java_version }}-linux-x64.rpm

- name: remove old java packages
  file: path="{{ install_temp_dir }}/{{ java_install_file }}" state=absent

- debug:
     msg: "Downloading {{ common.java_download }}"

- name: download java sdk rpm
  command : "wget --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3a%2F%2Fwww.oracle.com%2Ftechnetwork%2Fjava%2Fjavase%2Fdownloads%2Fjdk8-downloads-2133151.html; oraclelicense=accept-securebackup-cookie;' {{common.java_download}}"
  
- name: Move rpm
  command : "mv {{ java_install_file }}  {{ install_temp_dir }}/{{ java_install_file }}"  

#- name: download java sdk rpm
#  shell: "cd {{ install_temp_dir }} && curl -LO {{ common.java_download }} -H 'Cookie: oraclelicense=accept-securebackup-cookie'"

- name: install java sdk rpm
  shell: "rpm -Uvh --replacepkgs {{ install_temp_dir }}/{{ java_install_file }}"
  register: shell_result
  failed_when: "'error' in shell_result.stderr"

- name: configure default java
  shell: "alternatives --install /usr/bin/java java {{ common.java_home }}/bin/java 1"

- name: configure default java
  shell: "alternatives --set java {{ common.java_home }}/bin/java"

- name: set java jce distribution fact
  set_fact: java_jce_install_file=jce_policy-8.zip

- name: download java jce zip
  command : "wget --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3a%2F%2Fwww.oracle.com%2Ftechnetwork%2Fjava%2Fjavase%2Fdownloads%2Fjdk8-downloads-2133151.html; oraclelicense=accept-securebackup-cookie;' {{common.java_jce_download}}"

- name: Move rpm
  command : "mv {{java_jce_install_file}}  {{ install_temp_dir }}/{{ java_jce_install_file }}"

- name: update java with jce contents
  shell:
    unzip -o -j -q {{ install_temp_dir }}/{{ java_jce_install_file }} -d {{ common.java_home }}/jre/lib/security/

# Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is not defined and java_home == ''

# Set java_home fact to be used for other roles
- name: set java home fact
  set_fact: java_home={{ common.java_home }}
