---
- name: Create /opt/src
  file: path=/opt/src state=directory recurse=yes

- name: Create lib dir
  file: path={{common.sbt_lib_path_target}} state=directory recurse=yes

- name: Download sbt 
  get_url: url={{sbt_download_url}} 
    dest=/opt/src/{{common.sbt_archive_file}}

- name: Unpack sbt
  unarchive: src=/opt/src/{{common.sbt_archive_file}} dest={{common.sbt_lib_path_target}} copy=no

- name: Link sbt
  file: state=link src={{common.sbt_lib_path_target}}/sbt/bin/sbt dest={{common.sbt_link_target}}
